version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/dash
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
    volumes:
      - ./frontend/src:/app/src
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dash
    ports:
      - "5432:5432"

  # For production, consider adding:
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"

volumes:
  postgres_data: